############################################################################
# apps/wireless/wifi/wpa_hostapd_sources.mk
#
# Generated from the imported wpa_supplicant/hostapd Makefiles using the
# local .config files in their upstream source directories.
############################################################################

ifeq ($(CONFIG_WIRELESS_WIFI_WPA_SUPPLICANT),y)
PROGNAME += wpa_supplicant wpa_cli wpa_passphrase
PRIORITY += 90 100 100
STACKSIZE += $(CONFIG_WIRELESS_WIFI_WPA_SUPPLICANT_STACKSIZE)
STACKSIZE += $(CONFIG_WIRELESS_WIFI_WPA_CLI_STACKSIZE)
STACKSIZE += $(CONFIG_WIRELESS_WIFI_WPA_PASSPHRASE_STACKSIZE)
MODULE += $(CONFIG_WIRELESS_WIFI_WPA_SUPPLICANT)
MAINSRC += wpa_supplicant-2.11/wpa_supplicant/main.c
MAINSRC += wpa_supplicant-2.11/wpa_supplicant/wpa_cli.c
MAINSRC += wpa_supplicant-2.11/wpa_supplicant/wpa_passphrase.c
endif

ifeq ($(CONFIG_WIRELESS_WIFI_HOSTAPD),y)
PROGNAME += hostapd hostapd_cli
PRIORITY += 90 100
STACKSIZE += $(CONFIG_WIRELESS_WIFI_HOSTAPD_STACKSIZE)
STACKSIZE += $(CONFIG_WIRELESS_WIFI_HOSTAPD_CLI_STACKSIZE)
MODULE += $(CONFIG_WIRELESS_WIFI_HOSTAPD)
MAINSRC += hostapd-2.11/hostapd/main.c
MAINSRC += hostapd-2.11/hostapd/hostapd_cli.c
endif

ifneq ($(CONFIG_WIRELESS_WIFI_WPA_SUPPLICANT)$(CONFIG_WIRELESS_WIFI_HOSTAPD),)
WIFI_WPA_HOSTAPD_CFLAGS += -DOS_NO_C_LIB_DEFINES
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_BACKEND_FILE -DCONFIG_NO_CONFIG_WRITE
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_DRIVER_NL80211 -DCONFIG_LIBNL3_ROUTE
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_ELOOP_POLL
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_CTRL_IFACE
ifeq ($(CONFIG_ARCH_SIM),y)
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_CTRL_IFACE_UDP
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_TESTING_OPTIONS
else
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_CTRL_IFACE_UNIX
endif
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_CRYPTO_INTERNAL -DCONFIG_INTERNAL_LIBTOMMATH
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_TLS_INTERNAL -DCONFIG_TLS_INTERNAL_CLIENT -DCONFIG_TLS_INTERNAL_SERVER
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_NO_RANDOM_POOL -DCONFIG_DES -DCONFIG_SHA256
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_SHA384 -DCONFIG_SHA512
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_INTERNAL_SHA384 -DCONFIG_INTERNAL_SHA512 -DALL_DH_GROUPS -DCONFIG_ECC
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_IEEE80211R -DCONFIG_IEEE80211R_AP -DCONFIG_IEEE80211W
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_IEEE80211AC
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_IEEE80211AX
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_SUITEB -DCONFIG_SUITEB192
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_FILS -DCONFIG_OCV -DCONFIG_ERP
ifeq ($(CONFIG_ARCH_SIM),y)
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_SAE
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_SAE_PK
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_OWE
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_DPP -DCONFIG_DPP2
endif
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_WNM -DCONFIG_WNM_AP -DCONFIG_P2P -DCONFIG_AP -DNEED_AP_MLME
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_WPS -DEAP_WSC -DEAP_SERVER_WSC
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_HS20 -DCONFIG_INTERWORKING -DCONFIG_PROXYARP
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_SME -DCONFIG_GAS -DCONFIG_OFFCHANNEL
ifeq ($(CONFIG_ARCH_SIM),y)
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_GAS_SERVER
endif
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_BGSCAN_SIMPLE -DCONFIG_BGSCAN
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_AUTOSCAN_EXPONENTIAL -DCONFIG_AUTOSCAN_PERIODIC -DCONFIG_AUTOSCAN
WIFI_WPA_HOSTAPD_CFLAGS += -DEAP_TLS -DEAP_PEAP -DEAP_TTLS -DEAP_MD5 -DEAP_MSCHAPv2
WIFI_WPA_HOSTAPD_CFLAGS += -DEAP_GTC -DEAP_OTP -DEAP_LEAP -DEAP_FAST -DEAP_PSK -DEAP_PAX -DEAP_SAKE
WIFI_WPA_HOSTAPD_CFLAGS += -DEAP_GPSK -DEAP_GPSK_SHA256 -DEAP_IKEV2 -DEAP_TNC
WIFI_WPA_HOSTAPD_CFLAGS += -DIEEE8021X_EAPOL -DEAP_SERVER -DEAP_SERVER_IDENTITY
WIFI_WPA_HOSTAPD_CFLAGS += -DEAP_SERVER_MD5 -DEAP_SERVER_TLS -DEAP_SERVER_PEAP -DEAP_SERVER_TTLS
WIFI_WPA_HOSTAPD_CFLAGS += -DEAP_SERVER_MSCHAPV2 -DEAP_SERVER_GTC -DEAP_SERVER_PSK -DEAP_SERVER_PAX
WIFI_WPA_HOSTAPD_CFLAGS += -DEAP_SERVER_SAKE -DEAP_SERVER_GPSK
WIFI_WPA_HOSTAPD_CFLAGS += -DEAP_SERVER_FAST -DEAP_SERVER_IKEV2 -DEAP_TLS_FUNCS
WIFI_WPA_HOSTAPD_CFLAGS += -DHOSTAPD -DHOSTAPD_DUMP_STATE -DCONFIG_FULL_DYNAMIC_VLAN
WIFI_WPA_HOSTAPD_CFLAGS += -DCONFIG_ETH_P_OUI
CFLAGS += $(WIFI_WPA_HOSTAPD_CFLAGS)

ifeq ($(CONFIG_ARCH_SIM),y)
CSRCS += wpa_supplicant-2.11/src/common/sae.c
CSRCS += wpa_supplicant-2.11/src/common/sae_pk.c
CSRCS += wpa_supplicant-2.11/src/common/dragonfly.c
CSRCS += wpa_supplicant-2.11/src/common/dpp.c
CSRCS += wpa_supplicant-2.11/src/common/dpp_auth.c
CSRCS += wpa_supplicant-2.11/src/common/dpp_backup.c
CSRCS += wpa_supplicant-2.11/src/common/dpp_crypto.c
CSRCS += wpa_supplicant-2.11/src/common/dpp_pkex.c
CSRCS += wpa_supplicant-2.11/src/common/dpp_reconfig.c
CSRCS += wpa_supplicant-2.11/src/common/dpp_tcp.c
CSRCS += wpa_supplicant-2.11/src/common/gas_server.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/dpp_supplicant.c
CSRCS += wpa_supplicant-2.11/src/ap/dpp_hostapd.c
CSRCS += wpa_supplicant-2.11/src/ap/gas_query_ap.c
CSRCS += wpa_supplicant-2.11/src/utils/json.c
endif
CSRCS += wpa_supplicant-2.11/wpa_supplicant/config.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/notify.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/bss.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/eap_register.c
CSRCS += wpa_supplicant-2.11/src/utils/common.c
CSRCS += wpa_supplicant-2.11/src/utils/config.c
CSRCS += wpa_supplicant-2.11/src/utils/wpa_debug.c
CSRCS += wpa_supplicant-2.11/src/utils/wpabuf.c
CSRCS += wpa_supplicant-2.11/src/utils/bitfield.c
CSRCS += wpa_supplicant-2.11/src/utils/ip_addr.c
CSRCS += wpa_supplicant-2.11/src/utils/crc32.c
CSRCS += wpa_supplicant-2.11/src/common/ptksa_cache.c
CSRCS += wpa_supplicant-2.11/src/rsn_supp/pmksa_cache.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/twt.c
CSRCS += wpa_supplicant-2.11/src/utils/os_internal.c
CSRCS += wpa_supplicant-2.11/src/utils/eloop.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/config_file.c
CSRCS += wpa_supplicant-2.11/src/common/ocv.c
CSRCS += wpa_supplicant-2.11/src/rsn_supp/wpa_ft.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/wnm_sta.c
CSRCS += wpa_supplicant-2.11/src/rsn_supp/wpa.c
CSRCS += wpa_supplicant-2.11/src/rsn_supp/preauth.c
CSRCS += wpa_supplicant-2.11/src/rsn_supp/wpa_ie.c
CSRCS += wpa_supplicant-2.11/src/common/wpa_common.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/p2p_supplicant.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/p2p_supplicant_sd.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_utils.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_parse.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_build.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_go_neg.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_sd.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_pd.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_invitation.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_dev_disc.c
CSRCS += wpa_supplicant-2.11/src/p2p/p2p_group.c
CSRCS += wpa_supplicant-2.11/src/ap/p2p_hostapd.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/hs20_supplicant.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/interworking.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/rrm.c
CSRCS += wpa_supplicant-2.11/src/ap/rrm.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/op_classes.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/wmm_ac.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/robust_av.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_tls.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_peap.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_peap_common.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_ttls.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_md5.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_mschapv2.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/mschapv2.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_gtc.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_otp.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_leap.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_fast.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_fast_pac.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_fast_common.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_psk.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_psk_common.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_pax.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_pax_common.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_sake.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_sake_common.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_gpsk.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_gpsk_common.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/wps_supplicant.c
CSRCS += wpa_supplicant-2.11/src/utils/uuid.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_wsc.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_wsc_common.c
CSRCS += wpa_supplicant-2.11/src/wps/wps.c
CSRCS += wpa_supplicant-2.11/src/wps/wps_common.c
CSRCS += wpa_supplicant-2.11/src/wps/wps_attr_parse.c
CSRCS += wpa_supplicant-2.11/src/wps/wps_attr_build.c
CSRCS += wpa_supplicant-2.11/src/wps/wps_attr_process.c
CSRCS += wpa_supplicant-2.11/src/wps/wps_dev_attr.c
CSRCS += wpa_supplicant-2.11/src/wps/wps_enrollee.c
CSRCS += wpa_supplicant-2.11/src/wps/wps_registrar.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_ikev2.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/ikev2.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_ikev2_common.c
CSRCS += wpa_supplicant-2.11/src/eap_common/ikev2_common.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_tnc.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/tncc.c
CSRCS += wpa_supplicant-2.11/src/eapol_supp/eapol_supp_sm.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_methods.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/ap.c
CSRCS += wpa_supplicant-2.11/src/ap/hostapd.c
CSRCS += wpa_supplicant-2.11/src/ap/wpa_auth_glue.c
CSRCS += wpa_supplicant-2.11/src/ap/utils.c
CSRCS += wpa_supplicant-2.11/src/ap/authsrv.c
CSRCS += wpa_supplicant-2.11/src/ap/ap_config.c
CSRCS += wpa_supplicant-2.11/src/ap/sta_info.c
CSRCS += wpa_supplicant-2.11/src/ap/tkip_countermeasures.c
CSRCS += wpa_supplicant-2.11/src/ap/ap_mlme.c
CSRCS += wpa_supplicant-2.11/src/ap/ieee802_1x.c
CSRCS += wpa_supplicant-2.11/src/eapol_auth/eapol_auth_sm.c
CSRCS += wpa_supplicant-2.11/src/ap/ieee802_11_auth.c
CSRCS += wpa_supplicant-2.11/src/ap/ieee802_11_shared.c
CSRCS += wpa_supplicant-2.11/src/ap/drv_callbacks.c
CSRCS += wpa_supplicant-2.11/src/ap/ap_drv_ops.c
CSRCS += wpa_supplicant-2.11/src/ap/beacon.c
CSRCS += wpa_supplicant-2.11/src/ap/bss_load.c
CSRCS += wpa_supplicant-2.11/src/ap/eap_user_db.c
CSRCS += wpa_supplicant-2.11/src/ap/neighbor_db.c
CSRCS += wpa_supplicant-2.11/src/ap/wnm_ap.c
CSRCS += wpa_supplicant-2.11/src/ap/fils_hlp.c
CSRCS += wpa_supplicant-2.11/src/ap/ieee802_11_ht.c
CSRCS += wpa_supplicant-2.11/src/ap/ieee802_11_vht.c
CSRCS += wpa_supplicant-2.11/src/ap/ieee802_11_he.c
CSRCS += wpa_supplicant-2.11/src/ap/ctrl_iface_ap.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_identity.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_methods.c
CSRCS += wpa_supplicant-2.11/src/ap/wmm.c
CSRCS += wpa_supplicant-2.11/src/ap/ap_list.c
CSRCS += wpa_supplicant-2.11/src/ap/comeback_token.c
CSRCS += wpa_supplicant-2.11/src/pasn/pasn_responder.c
CSRCS += wpa_supplicant-2.11/src/ap/ieee802_11.c
CSRCS += wpa_supplicant-2.11/src/ap/hw_features.c
CSRCS += wpa_supplicant-2.11/src/ap/dfs.c
CSRCS += wpa_supplicant-2.11/src/ap/wps_hostapd.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_wsc.c
CSRCS += wpa_supplicant-2.11/src/ap/gas_serv.c
CSRCS += wpa_supplicant-2.11/src/ap/hs20.c
CSRCS += wpa_supplicant-2.11/src/ap/wpa_auth.c
CSRCS += wpa_supplicant-2.11/src/ap/wpa_auth_ie.c
CSRCS += wpa_supplicant-2.11/src/ap/pmksa_cache_auth.c
CSRCS += wpa_supplicant-2.11/src/crypto/ms_funcs.c
CSRCS += wpa_supplicant-2.11/src/eap_common/chap.c
CSRCS += wpa_supplicant-2.11/src/eap_peer/eap_tls_common.c
CSRCS += wpa_supplicant-2.11/src/crypto/crypto_internal-rsa.c
CSRCS += wpa_supplicant-2.11/src/crypto/tls_internal.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_common.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_record.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_cred.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_client.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_client_write.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_client_read.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_client_ocsp.c
CSRCS += wpa_supplicant-2.11/src/tls/rsa.c
CSRCS += wpa_supplicant-2.11/src/tls/x509v3.c
CSRCS += wpa_supplicant-2.11/src/tls/pkcs1.c
CSRCS += wpa_supplicant-2.11/src/tls/pkcs5.c
CSRCS += wpa_supplicant-2.11/src/tls/pkcs8.c
CSRCS += wpa_supplicant-2.11/src/crypto/crypto_internal-cipher.c
CSRCS += wpa_supplicant-2.11/src/crypto/crypto_internal-modexp.c
CSRCS += wpa_supplicant-2.11/src/tls/bignum.c
CSRCS += wpa_supplicant-2.11/src/crypto/crypto_internal.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-internal.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-internal-dec.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-unwrap.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-omac1.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-wrap.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-encblock.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-eax.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-cbc.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-internal-enc.c
CSRCS += wpa_supplicant-2.11/src/crypto/md5.c
CSRCS += wpa_supplicant-2.11/src/crypto/md5-internal.c
CSRCS += wpa_supplicant-2.11/src/crypto/md4-internal.c
CSRCS += wpa_supplicant-2.11/src/crypto/rc4.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha256.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha256-prf.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha256-internal.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha384.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha384-prf.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha384-kdf.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha384-internal.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha512.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha512-prf.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha512-kdf.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha512-internal.c
CSRCS += wpa_supplicant-2.11/src/tls/asn1.c
CSRCS += wpa_supplicant-2.11/src/crypto/dh_groups.c
CSRCS += wpa_supplicant-2.11/src/crypto/dh_group5.c
CSRCS += wpa_supplicant-2.11/src/common/ctrl_iface_common.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/ctrl_iface.c
ifeq ($(CONFIG_ARCH_SIM),y)
CSRCS += wpa_supplicant-2.11/wpa_supplicant/ctrl_iface_udp.c
else
CSRCS += wpa_supplicant-2.11/wpa_supplicant/ctrl_iface_unix.c
endif
CSRCS += wpa_supplicant-2.11/src/utils/base64.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/sme.c
CSRCS += wpa_supplicant-2.11/src/common/ieee802_11_common.c
CSRCS += wpa_supplicant-2.11/src/common/hw_features_common.c
CSRCS += wpa_supplicant-2.11/src/eap_common/eap_common.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha1.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha1-prf.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha1-internal.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha1-pbkdf2.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha1-tprf.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha1-tlsprf.c
CSRCS += wpa_supplicant-2.11/src/crypto/des-internal.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/bgscan_simple.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/bgscan.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/autoscan_exponential.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/autoscan_periodic.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/autoscan.c
CSRCS += wpa_supplicant-2.11/src/common/gas.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/gas_query.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/offchannel.c
CSRCS += wpa_supplicant-2.11/src/drivers/driver_common.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/wpa_supplicant.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/events.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/bssid_ignore.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/wpas_glue.c
CSRCS += wpa_supplicant-2.11/wpa_supplicant/scan.c
CSRCS += wpa_supplicant-2.11/src/drivers/driver_nl80211.c
CSRCS += wpa_supplicant-2.11/src/drivers/driver_nl80211_capa.c
CSRCS += wpa_supplicant-2.11/src/drivers/driver_nl80211_event.c
CSRCS += wpa_supplicant-2.11/src/drivers/driver_nl80211_monitor.c
CSRCS += wpa_supplicant-2.11/src/drivers/driver_nl80211_scan.c
CSRCS += wpa_supplicant-2.11/src/drivers/netlink.c
CSRCS += wpa_supplicant-2.11/src/drivers/rfkill.c
CSRCS += wpa_supplicant-2.11/src/utils/radiotap.c
CSRCS += wpa_supplicant-2.11/src/drivers/linux_ioctl.c
CSRCS += wpa_supplicant-2.11/src/drivers/drivers.c
CSRCS += wpa_supplicant-2.11/src/l2_packet/l2_packet_linux.c
CSRCS += wpa_supplicant-2.11/src/common/wpa_ctrl.c
CSRCS += wpa_supplicant-2.11/src/common/cli.c
CSRCS += wpa_supplicant-2.11/src/utils/edit_simple.c
CSRCS += hostapd-2.11/hostapd/config_file.c
CSRCS += wpa_supplicant-2.11/src/ap/preauth_auth.c
CSRCS += wpa_supplicant-2.11/src/eapol_auth/eapol_auth_dump.c
CSRCS += wpa_supplicant-2.11/src/radius/radius.c
CSRCS += wpa_supplicant-2.11/src/radius/radius_client.c
CSRCS += wpa_supplicant-2.11/src/radius/radius_das.c
CSRCS += wpa_supplicant-2.11/src/ap/accounting.c
CSRCS += wpa_supplicant-2.11/src/ap/vlan_init.c
CSRCS += wpa_supplicant-2.11/src/ap/vlan_ifconfig.c
CSRCS += wpa_supplicant-2.11/src/ap/vlan.c
CSRCS += wpa_supplicant-2.11/src/ap/vlan_full.c
CSRCS += wpa_supplicant-2.11/src/ap/vlan_util.c
CSRCS += hostapd-2.11/hostapd/ctrl_iface.c
CSRCS += wpa_supplicant-2.11/src/ap/wpa_auth_ft.c
CSRCS += wpa_supplicant-2.11/src/ap/eth_p_oui.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_md5.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_tls.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_peap.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_ttls.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_mschapv2.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_gtc.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_psk.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_pax.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_sake.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_gpsk.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_fast.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_ikev2.c
CSRCS += wpa_supplicant-2.11/src/eap_server/ikev2.c
CSRCS += hostapd-2.11/hostapd/eap_register.c
CSRCS += wpa_supplicant-2.11/src/eap_server/eap_server_tls_common.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_server.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_server_write.c
CSRCS += wpa_supplicant-2.11/src/tls/tlsv1_server_read.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-siv.c
CSRCS += wpa_supplicant-2.11/src/crypto/aes-ctr.c
CSRCS += wpa_supplicant-2.11/src/crypto/sha256-kdf.c
CSRCS += wpa_supplicant-2.11/src/pasn/pasn_common.c
CSRCS += wpa_supplicant-2.11/src/ap/x_snoop.c
CSRCS += wpa_supplicant-2.11/src/ap/dhcp_snoop.c
endif
