############################################################################
# apps/examples/max30102_demo/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_MAX30102_DEMO_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_MAX30102_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_MAX30102_DEMO_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_MAX30102_DEMO)

MAINSRC = max30102_demo_main.c

include $(APPDIR)/Application.mk
