############################################################################
# apps/examples/aw8697demo/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_AW8697DEMO_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_AW8697DEMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_AW8697DEMO_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_AW8697DEMO)

MAINSRC = aw8697demo_main.c

include $(APPDIR)/Application.mk
