############################################################################
# apps/wireless/esp_hosted_ng/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

context::

clean::

distclean:: clean

