############################################################################
# apps/examples/wifi_hwsim_sta/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_WIFI_HWSIM_STA_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_WIFI_HWSIM_STA_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_WIFI_HWSIM_STA_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_WIFI_HWSIM_STA)

MAINSRC = wifi_hwsim_sta_main.c

include $(APPDIR)/Application.mk
