############################################################################
# apps/wireless/bluetooth/ble_periph/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

MAINSRC = ble_periph_main.c

PROGNAME = $(CONFIG_BLE_PERIPH_DEMO_PROGNAME)
PRIORITY = $(CONFIG_BLE_PERIPH_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_BLE_PERIPH_DEMO_STACKSIZE)
MODULE = $(CONFIG_BLE_PERIPH_DEMO)

include $(APPDIR)/Application.mk
