############################################################################
# apps/graphics/pinion/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PINION_ROOT = $(APPDIR)/graphics/pinion

CSRCS += pinion.c

VPATH += $(PINION_ROOT)/src

CFLAGS += ${INCDIR_PREFIX}$(PINION_ROOT)/include

include $(APPDIR)/Application.mk
