############################################################################
# apps/examples/bme280_dmo/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_BME280_DMO_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_BME280_DMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_BME280_DMO_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_BME280_DMO)

MAINSRC = bme280_dmo_main.c

include $(APPDIR)/Application.mk
