############################################################################
# apps/wireless/bluetooth/ble_gatt/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

MAINSRC = ble_gatt_main.c

PROGNAME = $(CONFIG_BLE_GATT_DEMO_PROGNAME)
PRIORITY = $(CONFIG_BLE_GATT_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_BLE_GATT_DEMO_STACKSIZE)
MODULE = $(CONFIG_BLE_GATT_DEMO)

include $(APPDIR)/Application.mk
