############################################################################
# apps/examples/esp32_wifi_demo/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_ESP32_WIFI_DEMO_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_ESP32_WIFI_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_ESP32_WIFI_DEMO_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_ESP32_WIFI_DEMO)

MAINSRC = esp32_wifi_demo_main.c

include $(APPDIR)/Application.mk
