############################################################################
# apps/wireless/bluetooth/ble_adv/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

MAINSRC = ble_adv_main.c

PROGNAME = $(CONFIG_BLE_ADV_DEMO_PROGNAME)
PRIORITY = $(CONFIG_BLE_ADV_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_BLE_ADV_DEMO_STACKSIZE)
MODULE = $(CONFIG_BLE_ADV_DEMO)

include $(APPDIR)/Application.mk

