############################################################################
# apps/examples/fgfx_demo/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_EXAMPLES_FGFX_DEMO_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_FGFX_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_FGFX_DEMO_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_FGFX_DEMO)

MAINSRC = fgfx_demo_main.c

include $(APPDIR)/Application.mk
