############################################################################
# apps/graphics/frender/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

FRENDER_ROOT = $(APPDIR)/graphics/frender

CSRCS += frender.c

VPATH += $(FRENDER_ROOT)/src

CFLAGS += ${INCDIR_PREFIX}$(FRENDER_ROOT)/include

include $(APPDIR)/Application.mk
