############################################################################
# apps/examples/lsm6dsox_demo/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_LSM6DSOX_DEMO_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_LSM6DSOX_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_LSM6DSOX_DEMO_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_LSM6DSOX_DEMO)

MAINSRC = lsm6dsox_demo_main.c

include $(APPDIR)/Application.mk
