############################################################################
# apps/examples/wifi_hwsim_ap/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_WIFI_HWSIM_AP_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_WIFI_HWSIM_AP_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_WIFI_HWSIM_AP_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_WIFI_HWSIM_AP)

MAINSRC = wifi_hwsim_ap_main.c

include $(APPDIR)/Application.mk
