############################################################################
# apps/examples/pinion_demo/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = $(CONFIG_EXAMPLES_PINION_DEMO_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_PINION_DEMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_PINION_DEMO_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_PINION_DEMO)

MAINSRC = pinion_demo_main.c

include $(APPDIR)/Application.mk
